// Form 1 Schema - Exact fields from CSV sheet
export default {
  // Step 1: Personal Information
  phone: {
    label: 'Mobile Number',
    type: 'tel',
    required: true,
    rules: ['required', 'phone'],
    placeholder: 'Enter your 10-digit mobile number',
    errorMessage: 'Please enter a valid Mobile',
  },
  otp: {
    label: 'Enter Verification Code',
    type: 'text',
    required: true,
    rules: ['required', 'otp'],
    placeholder: 'Enter the 4-digit code sent to your mobile',
    errorMessage: 'Please enter a valid 4 digit otp',
    maxLength: 4,
  },
  consentCreditCheck: {
    label: 'I authorize PW.com to access my credit information',
    type: 'checkbox',
    required: true,
    rules: ['required'],
    errorMessage: 'This field is required',
  },
  firstName: {
    label: 'First Name',
    type: 'text',
    required: true,
    rules: ['required', 'firstName'],
    placeholder: 'Enter your first name',
    errorMessage: 'Please enter a valid full name',
    maxLength: 26,
  },
  lastName: {
    label: 'Last Name',
    type: 'text',
    required: false,
    rules: [],
    placeholder: 'Enter your last name',
  },
  email: {
    label: 'Email Address',
    type: 'email',
    required: true,
    rules: ['required', 'email'],
    placeholder: 'you@example.com',
    errorMessage: 'Please enter a valid Email',
  },
  dateOfBirth: {
    label: 'Date of Birth (DOB)',
    type: 'date',
    required: true,
    rules: ['required', 'dobDate'],
    errorMessage: 'Please enter a valid Date of Birth',
  },
  city: {
    label: 'City',
    type: 'text',
    required: true,
    rules: ['required', 'city'],
    placeholder: 'Select or enter city',
    errorMessage: 'Plese select a city',
    searchType: true, // Auto Populated, search type
  },
  state: {
    label: 'State',
    type: 'select',
    required: true,
    rules: ['required'],
    placeholder: 'Select state',
    errorMessage: 'Plese select a state',
    searchType: true, // Auto Populated
    // Note: CSV says "Numeric Value" - will need to get actual state list with numeric IDs
    options: [
      { value: '1', label: 'Maharashtra' },
      { value: '2', label: 'Delhi' },
      { value: '3', label: 'Karnataka' },
      { value: '4', label: 'Tamil Nadu' },
      { value: '5', label: 'Gujarat' },
      { value: '6', label: 'West Bengal' },
      { value: '7', label: 'Rajasthan' },
      { value: '8', label: 'Uttar Pradesh' },
      { value: '9', label: 'Punjab' },
      { value: '10', label: 'Haryana' },
      { value: '11', label: 'Other' },
    ],
  },
  pinCode: {
    label: 'PIN Code',
    type: 'text',
    required: true,
    rules: ['required', 'zipCode'],
    placeholder: 'Enter 6-digit PIN code',
    errorMessage: 'Please select a pin code',
    maxLength: 6,
    searchType: true,
  },
  gender: {
    label: 'Gender',
    type: 'select',
    required: true,
    rules: ['required'],
    placeholder: 'Select gender',
    errorMessage: 'Please select a gender',
    options: [
      { value: 'male', label: 'Male' },
      { value: 'female', label: 'Female' },
      { value: 'others', label: 'Others' },
    ],
  },
  panNumber: {
    label: 'PAN Number',
    type: 'text',
    required: true,
    rules: ['required', 'pan'],
    placeholder: 'ABCDE1234F',
    errorMessage: 'Please Enter a Valid Pan',
    maxLength: 10,
  },

  // Step 2: Employment Details
  loanAmount: {
    label: 'Desired Loan Amount',
    type: 'number',
    required: true,
    rules: ['required', 'numeric'],
    placeholder: 'Enter desired loan amount',
    errorMessage: 'Please provide a desired loan amount',
  },
  employmentType: {
    label: 'Employment Type',
    type: 'select',
    required: true,
    rules: ['required'],
    placeholder: 'Select employment type',
    errorMessage: 'Please enter a valid Employment type',
    options: [
      { value: 'Salaried', label: 'Salaried' },
      { value: 'Self Employed', label: 'Self Employed' },
      { value: 'Student', label: 'Student' },
    ],
  },
  netMonthlyIncome: {
    label: 'Net Monthly Income',
    type: 'number',
    required: true,
    rules: ['required', 'numeric', 'netMonthlyIncome'],
    placeholder: 'Enter monthly income (max 8 digits)',
    errorMessage: 'Please enter a Net monthly income (not more than 8 numeric digit)',
  },
  companyName: {
    label: 'Company Name',
    type: 'text',
    required: true,
    rules: ['required'],
    placeholder: 'Enter company name',
    errorMessage: 'Please enter a valid company name',
  },
  modeOfSalary: {
    label: 'Mode of Salary',
    type: 'select',
    required: true,
    rules: ['required'],
    placeholder: 'Select mode of salary',
    errorMessage: 'Please select a mode of salary',
    options: [
      { value: 'bank_account', label: 'Bank Account' },
      { value: 'cash', label: 'Cash' },
      { value: 'cheque', label: 'Cheque' },
    ],
  },
  companyEmail: {
    label: 'Company Email Address',
    type: 'email',
    required: true,
    rules: ['required', 'email'],
    placeholder: 'company@example.com',
    errorMessage: 'Please enter a valid Email',
  },
  companyAddress: {
    label: 'Company Address',
    type: 'text',
    required: true,
    rules: ['required'],
    placeholder: 'Office door no/ Locality/area/landmark',
    errorMessage: 'Please enter a valid office locality/area',
    fullWidth: true,
  },
  companyCity: {
    label: 'Company City',
    type: 'text',
    required: true,
    rules: ['required', 'city'],
    placeholder: 'Select or enter city',
    errorMessage: 'Plese select a city',
    searchType: true,
  },
  companyEstate: {
    label: 'Company Estate',
    type: 'text',
    required: true,
    rules: ['required'],
    placeholder: 'Select estate',
    errorMessage: 'Plese select a estate',
    searchType: true,
  },
  companyPinCode: {
    label: 'Company PIN Code',
    type: 'text',
    required: true,
    rules: ['required', 'zipCode'],
    placeholder: 'Enter 6-digit PIN code',
    errorMessage: 'Please select a pin code',
    maxLength: 6,
    searchType: true,
  },

  // Step 3: Address Details
  currentAddress: {
    label: 'Current Address',
    type: 'text',
    required: true,
    rules: ['required'],
    placeholder: 'Enter locality/area',
    errorMessage: 'Please enter a valid locality/area',
    fullWidth: true,
  },
  address: {
    label: 'Address',
    type: 'text',
    required: true,
    rules: ['required'],
    placeholder: 'door no/ Locality/area/landmark',
    errorMessage: 'Please enter a valid locality/area',
    fullWidth: true,
  },
  mothersName: {
    label: 'Mothers Name',
    type: 'text',
    required: false,
    rules: [],
    placeholder: 'Enter mother\'s name',
  },
  loanPurpose: {
    label: 'Loan Purpose',
    type: 'text',
    required: false,
    rules: [],
    placeholder: 'Enter loan purpose',
  },
  currentResidentialType: {
    label: 'Current Residential Type',
    type: 'text',
    required: false,
    rules: [],
    placeholder: 'Enter residential type',
  },
  organizationType: {
    label: 'Organization Type',
    type: 'text',
    required: false,
    rules: [],
    placeholder: 'Enter organization type',
  },

  // Step organization - exactly as per CSV
  // Note: phone, otp, and consentCreditCheck are handled in the phone/OTP stage before the form
  steps: [
    // Step 1: Personal Information
    ['firstName', 'lastName', 'email', 'dateOfBirth', 'city', 'state', 'pinCode', 'gender', 'panNumber'],
    // Step 2: Employment Details
    ['loanAmount', 'employmentType', 'netMonthlyIncome', 'companyName', 'modeOfSalary', 'companyEmail', 'companyAddress', 'companyCity', 'companyEstate', 'companyPinCode'],
    // Step 3: Address Details
    ['currentAddress', 'address', 'mothersName', 'loanPurpose', 'currentResidentialType', 'organizationType'],
  ],
};
