// Form 1 Schema - Exact fields from CSV sheet
export default {
  // Step 1: Personal Information
  phone: {
    label: 'Mobile Number',
    type: 'tel',
    required: true,
    rules: ['required', 'phone'],
    placeholder: 'Enter your 10-digit mobile number',
    errorMessage: 'Please enter a valid Mobile',
  },
  otp: {
    label: 'Enter Verification Code',
    type: 'text',
    required: true,
    rules: ['required', 'otp'],
    placeholder: 'Enter the 4-digit code sent to your mobile',
    errorMessage: 'Please enter a valid 4 digit otp',
    maxLength: 4,
  },
  consentCreditCheck: {
    label: 'I authorize PW.com to access my credit information',
    type: 'checkbox',
    required: true,
    rules: ['required'],
    errorMessage: 'This field is required',
  },
  firstName: {
    label: 'First Name',
    type: 'text',
    required: true,
    rules: ['required', 'firstName'],
    placeholder: 'Enter your first name',
    errorMessage: 'Please enter a valid full name',
    maxLength: 26,
  },
  lastName: {
    label: 'Last Name',
    type: 'text',
    required: true,
    rules: ['required'],
    placeholder: 'Enter your last name',
    errorMessage: 'Last Name is required',
    maxLength: 26,
  },
  email: {
    label: 'Email Address',
    type: 'email',
    required: true,
    rules: ['required', 'email'],
    placeholder: 'you@example.com',
    errorMessage: 'Please enter a valid Email',
  },
  dateOfBirth: {
    label: 'Date of Birth (DOB)',
    type: 'date',
    required: true,
    rules: ['required', 'dobDate'],
    errorMessage: 'Please enter a valid Date of Birth',
  },
  city: {
    label: 'City',
    type: 'text',
    required: true,
    rules: ['required', 'city'],
    placeholder: 'Select or enter city',
    errorMessage: 'Plese select a city',
    searchType: true, // Auto Populated, search type
  },
  state: {
    label: 'State',
    type: 'select',
    required: true,
    rules: ['required'],
    placeholder: 'Select state',
    errorMessage: 'Plese select a state',
    searchType: true, // Auto Populated
    // Note: CSV specifies only valid Indian states, no "Other" option
    options: [
      { value: '1', label: 'Andhra Pradesh' },
      { value: '2', label: 'Arunachal Pradesh' },
      { value: '3', label: 'Assam' },
      { value: '4', label: 'Bihar' },
      { value: '5', label: 'Chhattisgarh' },
      { value: '6', label: 'Delhi' },
      { value: '7', label: 'Goa' },
      { value: '8', label: 'Gujarat' },
      { value: '9', label: 'Haryana' },
      { value: '10', label: 'Himachal Pradesh' },
      { value: '11', label: 'Jharkhand' },
      { value: '12', label: 'Karnataka' },
      { value: '13', label: 'Kerala' },
      { value: '14', label: 'Madhya Pradesh' },
      { value: '15', label: 'Maharashtra' },
      { value: '16', label: 'Manipur' },
      { value: '17', label: 'Meghalaya' },
      { value: '18', label: 'Mizoram' },
      { value: '19', label: 'Nagaland' },
      { value: '20', label: 'Odisha' },
      { value: '21', label: 'Punjab' },
      { value: '22', label: 'Rajasthan' },
      { value: '23', label: 'Sikkim' },
      { value: '24', label: 'Tamil Nadu' },
      { value: '25', label: 'Telangana' },
      { value: '26', label: 'Tripura' },
      { value: '27', label: 'Uttar Pradesh' },
      { value: '28', label: 'Uttarakhand' },
      { value: '29', label: 'West Bengal' },
      { value: '30', label: 'Puducherry' },
    ],
  },
  pinCode: {
    label: 'PIN Code',
    type: 'pincode',
    required: true,
    rules: ['required', 'zipCode'],
    placeholder: 'Enter 6-digit PIN code',
    errorMessage: 'Please select a pin code',
    maxLength: 6,
    searchType: true,
    cityFieldName: 'city',
    stateFieldName: 'state',
  },
  gender: {
    label: 'Gender',
    type: 'radio', // Changed to radio to use GenderField component
    required: true,
    rules: ['required'],
    placeholder: 'Select gender',
    errorMessage: 'Please select a gender',
    options: [
      { value: 'male', label: 'Male' },
      { value: 'female', label: 'Female' },
      { value: 'other', label: 'Other' }, // Changed 'others' to 'other' to match inspiration
    ],
  },
  panNumber: {
    label: 'PAN Number',
    type: 'text',
    required: true,
    rules: ['required', 'pan'],
    placeholder: 'ABCDE1234F',
    errorMessage: 'Please Enter a Valid Pan',
    maxLength: 10,
  },

  // Step 2: Employment Details
  loanAmount: {
    label: 'Desired Loan Amount',
    type: 'currency',
    required: true,
    rules: ['required', 'numeric', { type: 'min', params: [10000] }, { type: 'max', params: [100000000] }],
    placeholder: 'Enter desired loan amount',
    errorMessage: 'Please provide a desired loan amount (min ₹10,000, max ₹10,00,00,000)',
    min: 10000,
    max: 100000000,
  },
  employmentType: {
    label: 'Employment Type',
    type: 'select',
    required: true,
    rules: ['required'],
    placeholder: 'Select employment type',
    errorMessage: 'Please enter a valid Employment type',
    options: [
      { value: 'Salaried', label: 'Salaried' },
      { value: 'Self-employed professional', label: 'Self-employed professional' },
      { value: 'Self-employed business', label: 'Self-employed business' },
      { value: 'Student', label: 'Student' },
    ],
  },
  netMonthlyIncome: {
    label: 'Net Monthly Income',
    type: 'currency',
    required: true,
    rules: ['required', 'numeric', { type: 'min', params: [10000] }, { type: 'max', params: [10000000] }],
    placeholder: 'Enter monthly income',
    errorMessage: 'Please enter a Net monthly income (min ₹10,000, max ₹1,00,00,000)',
    min: 10000,
    max: 10000000,
  },
  companyName: {
    label: 'Company Name',
    type: 'text',
    required: true,
    rules: ['required'],
    placeholder: 'Enter company name',
    errorMessage: 'Please enter a valid company name',
  },
  modeOfSalary: {
    label: 'Mode of Salary',
    type: 'select',
    required: true,
    rules: ['required'],
    placeholder: 'Select mode of salary',
    errorMessage: 'Please select a mode of salary',
    options: [
      { value: 'bank_account', label: 'Bank Account' },
      { value: 'cash', label: 'Cash' },
      { value: 'cheque', label: 'Cheque' },
    ],
  },
  annualIncome: {
    label: 'Annual Income',
    type: 'currency',
    required: false, // Will be conditionally required
    rules: ['numeric', { type: 'min', params: [1] }],
    placeholder: 'Enter annual income',
    errorMessage: 'Please enter a valid annual income (greater than 0)',
    min: 1,
  },
  organizationName: {
    label: 'Organization Name',
    type: 'text',
    required: false, // Will be conditionally required
    rules: [],
    placeholder: 'Enter organization name',
    errorMessage: 'Please enter a valid organization name',
  },
  profession: {
    label: 'Profession',
    type: 'text',
    required: false, // Will be conditionally required
    rules: [],
    placeholder: 'Enter your profession',
    errorMessage: 'Please enter your profession',
  },
  annualTurnover: {
    label: 'Annual Turnover',
    type: 'currency',
    required: false, // Will be conditionally required
    rules: ['numeric', { type: 'min', params: [1] }],
    placeholder: 'Enter annual turnover',
    errorMessage: 'Please enter a valid annual turnover (greater than 0)',
    min: 1,
  },
  companyEmail: {
    label: 'Company Email Address',
    type: 'email',
    required: true,
    rules: ['required', 'email'],
    placeholder: 'company@example.com',
    errorMessage: 'Please enter a valid Email',
  },
  companyAddress: {
    label: 'Company Address',
    type: 'text',
    required: true,
    rules: ['required'],
    placeholder: 'Office door no/ Locality/area/landmark',
    errorMessage: 'Please enter a valid office locality/area',
    fullWidth: true,
  },
  companyCity: {
    label: 'Company City',
    type: 'text',
    required: true,
    rules: ['required', 'city'],
    placeholder: 'Select or enter city',
    errorMessage: 'Plese select a city',
    searchType: true,
  },
  companyState: {
    label: 'Company State',
    type: 'select',
    required: true,
    rules: ['required'],
    placeholder: 'Select state',
    errorMessage: 'Plese select a state',
    searchType: true,
    // All 30 Indian states with numeric values
    options: [
      { value: '1', label: 'Andhra Pradesh' },
      { value: '2', label: 'Arunachal Pradesh' },
      { value: '3', label: 'Assam' },
      { value: '4', label: 'Bihar' },
      { value: '5', label: 'Chhattisgarh' },
      { value: '6', label: 'Delhi' },
      { value: '7', label: 'Goa' },
      { value: '8', label: 'Gujarat' },
      { value: '9', label: 'Haryana' },
      { value: '10', label: 'Himachal Pradesh' },
      { value: '11', label: 'Jharkhand' },
      { value: '12', label: 'Karnataka' },
      { value: '13', label: 'Kerala' },
      { value: '14', label: 'Madhya Pradesh' },
      { value: '15', label: 'Maharashtra' },
      { value: '16', label: 'Manipur' },
      { value: '17', label: 'Meghalaya' },
      { value: '18', label: 'Mizoram' },
      { value: '19', label: 'Nagaland' },
      { value: '20', label: 'Odisha' },
      { value: '21', label: 'Punjab' },
      { value: '22', label: 'Rajasthan' },
      { value: '23', label: 'Sikkim' },
      { value: '24', label: 'Tamil Nadu' },
      { value: '25', label: 'Telangana' },
      { value: '26', label: 'Tripura' },
      { value: '27', label: 'Uttar Pradesh' },
      { value: '28', label: 'Uttarakhand' },
      { value: '29', label: 'West Bengal' },
      { value: '30', label: 'Puducherry' },
    ],
  },
  companyPinCode: {
    label: 'Company PIN Code',
    type: 'pincode',
    required: true,
    rules: ['required', 'zipCode'],
    placeholder: 'Enter 6-digit PIN code',
    errorMessage: 'Please select a pin code',
    maxLength: 6,
    searchType: true,
    cityFieldName: 'companyCity',
    stateFieldName: 'companyState',
  },

  // Step 3: Address Details
  currentAddress: {
    label: 'Current Address',
    type: 'text',
    required: true,
    rules: ['required'],
    placeholder: 'Enter locality/area',
    errorMessage: 'Please enter a valid locality/area',
    fullWidth: true,
  },
  address: {
    label: 'Address',
    type: 'text',
    required: true,
    rules: ['required'],
    placeholder: 'door no/ Locality/area/landmark',
    errorMessage: 'Please enter a valid locality/area',
    fullWidth: true,
  },
  mothersName: {
    label: 'Mothers Name',
    type: 'text',
    required: false,
    rules: [],
    placeholder: 'Enter mother\'s name',
  },
  loanPurpose: {
    label: 'Loan Purpose',
    type: 'select',
    required: false,
    rules: [],
    placeholder: 'Select loan purpose',
    options: [
      { value: 'Medical Emergency', label: 'Medical Emergency' },
      { value: 'Home Renovation', label: 'Home Renovation' },
      { value: 'Wedding /Marriage', label: 'Wedding /Marriage' },
      { value: 'Travel / Vacation', label: 'Travel / Vacation' },
      { value: 'Debt Consolidation', label: 'Debt Consolidation' },
      { value: 'Others', label: 'Others' },
    ],
  },
  currentResidentialType: {
    label: 'Current Residential Type',
    type: 'select',
    required: false,
    rules: [],
    placeholder: 'Select residential type',
    options: [
      { value: 'Owned', label: 'Owned' },
      { value: 'Rented', label: 'Rented' },
      { value: 'Living with Parents', label: 'Living with Parents' },
      { value: 'Others', label: 'Others' },
    ],
  },
  organizationType: {
    label: 'Organization Type',
    type: 'select',
    required: false,
    rules: [],
    placeholder: 'Select organization type',
    options: [
      { value: 'Private Limited Company', label: 'Private Limited Company' },
      { value: 'Public Sector /Government', label: 'Public Sector /Government' },
      { value: 'Partnership Firm', label: 'Partnership Firm' },
      { value: 'Proprietorship', label: 'Proprietorship' },
      { value: 'Public Limited Company', label: 'Public Limited Company' },
      { value: 'Trust /NGO', label: 'Trust /NGO' },
      { value: 'Others', label: 'Others' },
    ],
  },

  // Step organization - exactly as per CSV
  // Note: phone and otp are handled by AuthForm component, not in these steps
  steps: [
    // Step 1: Personal Information
    ['firstName', 'lastName', 'email', 'dateOfBirth', 'city', 'state', 'pinCode', 'gender', 'panNumber'],
    // Step 2: Employment Details
    // Include all employment-related fields (visibility handled conditionally in Form1.jsx)
    ['loanAmount', 'employmentType', 'netMonthlyIncome', 'companyName', 'modeOfSalary', 'annualIncome', 'organizationName', 'profession', 'annualTurnover', 'companyEmail', 'companyAddress', 'companyCity', 'companyState', 'companyPinCode'],
    // Step 3: Address Details
    ['currentAddress', 'address', 'mothersName', 'loanPurpose', 'currentResidentialType', 'organizationType'],
  ],
};
