// Form 2 Schema - Simplified form for quick loan eligibility check
// Note: Phone number and consent are handled in AuthForm component during authentication
export default {
  firstName: {
    label: 'First Name',
    type: 'text',
    required: true,
    rules: ['required', 'firstName'],
    placeholder: 'Enter your first name',
    errorMessage: 'Please enter a valid first name',
    maxLength: 26,
  },
  lastName: {
    label: 'Last Name',
    type: 'text',
    required: false,
    rules: [],
    placeholder: 'Enter your last name',
  },
  dateOfBirth: {
    label: 'Date of Birth',
    type: 'date',
    required: true,
    rules: ['required', 'dobDate'],
    placeholder: 'Select your date of birth',
    errorMessage: 'Please enter a valid date of birth (age 21-55)',
  },
  email: {
    label: 'Email Address',
    type: 'email',
    required: true,
    rules: ['required', 'email'],
    placeholder: 'you@example.com',
    errorMessage: 'Please enter a valid Email',
  },
  loanAmount: {
    label: 'Desired Loan Amount',
    type: 'currency',
    required: true,
    rules: ['required', 'numeric', { type: 'min', params: [10000] }, { type: 'max', params: [100000000] }],
    placeholder: 'Enter desired loan amount',
    errorMessage: 'Please provide a desired loan amount (min ₹10,000, max ₹10,00,00,000)',
    min: 10000,
    max: 100000000,
  },
  loanPurpose: {
    label: 'Loan Purpose',
    type: 'select',
    required: false,
    rules: [],
    placeholder: 'Select loan purpose',
    options: [
      { value: 'Medical Emergency', label: 'Medical Emergency' },
      { value: 'Home Renovation', label: 'Home Renovation' },
      { value: 'Wedding /Marriage', label: 'Wedding /Marriage' },
      { value: 'Travel / Vacation', label: 'Travel / Vacation' },
      { value: 'Debt Consolidation', label: 'Debt Consolidation' },
      { value: 'Others', label: 'Others' },
    ],
  },
  employmentType: {
    label: 'Employment Type',
    type: 'select',
    required: true,
    rules: ['required'],
    placeholder: 'Select employment type',
    errorMessage: 'Please enter a valid Employment type',
    options: [
      { value: 'Salaried', label: 'Salaried' },
      { value: 'Self-employed professional', label: 'Self-employed professional' },
      { value: 'Self-employed business', label: 'Self-employed business' },
      { value: 'Student', label: 'Student' },
    ],
  },
  netMonthlyIncome: {
    label: 'Net Monthly Income',
    type: 'currency',
    required: false, // Will be conditionally required
    rules: ['numeric', { type: 'min', params: [10000] }, { type: 'max', params: [10000000] }],
    placeholder: 'Enter monthly income',
    errorMessage: 'Please enter a Net monthly income (min ₹10,000, max ₹1,00,00,000)',
    min: 10000,
    max: 10000000,
  },
  pinCode: {
    label: 'PIN Code',
    type: 'pincode',
    required: true,
    rules: ['required', 'zipCode'],
    placeholder: 'Enter 6-digit PIN code',
    errorMessage: 'Please select a pin code',
    maxLength: 6,
    searchType: true,
    cityFieldName: 'city',
    stateFieldName: 'state',
  },
  city: {
    label: 'City',
    type: 'text',
    required: true,
    rules: ['required', 'city'],
    placeholder: 'Select or enter city',
    errorMessage: 'Please select a city',
    searchType: true, // Auto Populated
  },
  state: {
    label: 'State',
    type: 'select',
    required: true,
    rules: ['required'],
    placeholder: 'Select state',
    errorMessage: 'Please select a state',
    searchType: true, // Auto Populated
    options: [
      { value: '1', label: 'Andhra Pradesh' },
      { value: '2', label: 'Arunachal Pradesh' },
      { value: '3', label: 'Assam' },
      { value: '4', label: 'Bihar' },
      { value: '5', label: 'Chhattisgarh' },
      { value: '6', label: 'Delhi' },
      { value: '7', label: 'Goa' },
      { value: '8', label: 'Gujarat' },
      { value: '9', label: 'Haryana' },
      { value: '10', label: 'Himachal Pradesh' },
      { value: '11', label: 'Jharkhand' },
      { value: '12', label: 'Karnataka' },
      { value: '13', label: 'Kerala' },
      { value: '14', label: 'Madhya Pradesh' },
      { value: '15', label: 'Maharashtra' },
      { value: '16', label: 'Manipur' },
      { value: '17', label: 'Meghalaya' },
      { value: '18', label: 'Mizoram' },
      { value: '19', label: 'Nagaland' },
      { value: '20', label: 'Odisha' },
      { value: '21', label: 'Punjab' },
      { value: '22', label: 'Rajasthan' },
      { value: '23', label: 'Sikkim' },
      { value: '24', label: 'Tamil Nadu' },
      { value: '25', label: 'Telangana' },
      { value: '26', label: 'Tripura' },
      { value: '27', label: 'Uttar Pradesh' },
      { value: '28', label: 'Uttarakhand' },
      { value: '29', label: 'West Bengal' },
      { value: '30', label: 'Puducherry' },
    ],
  },
};

